apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: loja-veloz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: zPirataa/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PEDIDOS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: loja-config
                  key: PEDIDOS_SERVICE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
