apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: loja-veloz
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
