apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: loja-veloz
type: Opaque
data:
  POSTGRES_USER: bG9qYV91c2Vy
  POSTGRES_PASSWORD: bG9qYV9wYXNzd29yZA==
  POSTGRES_DB: bG9qYV9wZWRpZG9z
