apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-pagamentos
  namespace: loja-veloz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servico-pagamentos
  template:
    metadata:
      labels:
        app: servico-pagamentos
    spec:
      containers:
        - name: servico-pagamentos
          image: zPirataa/servico-pagamentos:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
